services:
  wp:
    image: wordpress:latest
    user: "${UID}:${GID}"
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db
    volumes:
      - ./wp:/var/www/html
      - ./wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini 

  db:
    image: mysql:latest
    user: "${UID}:${GID}"
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "9090:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  wp:
  db:
