version: '3.1'
services:
  db:
    image: mariadb:latest
    restart: always
    user: mysql
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_DATABASE: xyz
      MYSQL_USER: xyz
      MYSQL_PASSWORD: xyz
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql
  wordpress:
      depends_on:
      - db
      image: wordpress:latest
      restart: always
      ports:
        - 8080:80
      environment:
        WORDPRESS_DB_HOST: db
        WORDPRESS_DB_USER: xyz
        WORDPRESS_DB_PASSWORD: xyz
        WORDPRESS_DB_NAME: xyz
        TAR_OPTIONS: --no-same-owner
      volumes:
        - ./wordpress:/var/www/html
        - ./wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini 
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  db:
  wordpress:
  phpmyadmin:
