version: '3.1'
services:
  db:
    image: mariadb:latest
    restart: always
    user: mysql
    environment:
      MYSQL_DATABASE: xyz
      MYSQL_USER: xyz
      MYSQL_PASSWORD: xyz
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql
  wordpress:
      depends_on:
      - db
      image: wordpress:latest
      restart: always
      user: root
      ports:
        - 80:80
      environment:
        WORDPRESS_DB_HOST: db
        WORDPRESS_DB_USER: xyz
        WORDPRESS_DB_PASSWORD: xyz
        WORDPRESS_DB_NAME: xyz
        TAR_OPTIONS: --no-same-owner
      volumes:
        - ./wordpress:/var/www/html
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  db:
  wordpress:
  phpmyadmin:
